"""Executive dashboard."""
from __future__ import annotations

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from foodcost.ai_engine.insights import generate_insights, _pretty
from ui import theme
from ui.theme import fmt_money, fmt_pct


def render(b) -> None:
    pos, profit, var = b.pos, b.profit, b.variance

    total_spend = float(b.purchases["extended_price"].sum())
    revenue = float(pos["revenue"].sum())
    theo_cost = float(profit["food_cost"].sum())
    waste = float(var["est_waste_dollars"].sum())
    fc_pct = theo_cost / revenue * 100 if revenue else 0
    actual_fc_pct = total_spend / revenue * 100 if revenue else 0

    period = ""
    try:
        s = pd.to_datetime(pos["period_start"]).min()
        e = pd.to_datetime(pos["period_end"]).max()
        period = f"{s:%b %d} – {e:%b %d, %Y}"
    except Exception:
        pass
    n_loc = pos["location"].nunique()

    theme.hero(
        "Executive Command Center",
        f"{period} · {n_loc} locations · "
        f"{b.purchases['invoice_no'].nunique()} invoices · "
        f"{int(pos['qty_sold'].sum()):,} items sold",
    )

    theme.metric_row([
        ("Net Sales", fmt_money(revenue),
         f"{int(pos['qty_sold'].sum()):,} items", "neutral"),
        ("Total Food Purchases", fmt_money(total_spend),
         f"{actual_fc_pct:,.1f}% of sales", "bad" if actual_fc_pct > 35 else "neutral"),
        ("Theoretical Food Cost", fmt_money(theo_cost),
         f"{fc_pct:,.1f}% of sales", "good" if fc_pct < 32 else "bad"),
        ("Est. Waste / Variance", fmt_money(waste),
         f"{waste / revenue * 100 if revenue else 0:,.1f}% of sales",
         "bad" if waste / max(revenue, 1) > 0.03 else "neutral"),
        ("Gross Profit (Theo.)", fmt_money(revenue - theo_cost),
         f"{100 - fc_pct:,.1f}% margin", "good"),
    ])

    # ------------------------------------------------ top insights
    theme.section("Top Recommended Actions",
                  "generated by the insight engine — full list on the AI Insights page")
    insights = _cached_insights(b)
    for ins in insights[:4]:
        st.markdown(theme.insight_card(
            ins.severity, ins.title, ins.body, ins.action, ins.impact_dollars),
            unsafe_allow_html=True)

    # ------------------------------------------------ charts row
    c1, c2 = st.columns([1.15, 1])
    with c1:
        theme.section("Purchases vs Theoretical Usage by Category")
        from foodcost.costing.variance import category_variance
        cat = category_variance(var)
        cat = cat[cat["purchased_dollars"] > 0]
        fig = go.Figure()
        fig.add_bar(name="Purchased", x=cat["category"], y=cat["purchased_dollars"],
                    marker_color=theme.BLUE)
        fig.add_bar(name="Theoretical usage", x=cat["category"], y=cat["theo_cost"],
                    marker_color=theme.ACCENT)
        fig.update_layout(barmode="group", height=340,
                          yaxis_title=None, xaxis_title=None,
                          yaxis_tickprefix="$", yaxis_tickformat=",.0f")
        st.plotly_chart(fig, use_container_width=True)
    with c2:
        theme.section("Highest Waste-Risk Ingredients")
        top = var[var["est_waste_dollars"] > 0].nlargest(8, "waste_risk")
        fig = px.bar(top.sort_values("waste_risk"),
                     x="waste_risk", y="ingredient_clean", orientation="h",
                     color="waste_risk", color_continuous_scale=["#C9D4E4", theme.RED],
                     labels={"waste_risk": "risk score", "ingredient_clean": ""})
        fig.update_layout(height=340, coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)

    # ------------------------------------------------ margins + price moves
    c3, c4 = st.columns(2)
    p = profit[(profit["revenue"] > 300) & profit["food_cost_pct"].notna()].copy()
    p["name"] = p["recipe"].map(_pretty)
    with c3:
        theme.section("Best Margin Menu Items", "min $300 revenue")
        best = p.nsmallest(7, "food_cost_pct")[["name", "qty_sold", "revenue",
                                                "food_cost_pct"]]
        _margin_table(best, good=True)
    with c4:
        theme.section("Tightest Margin Menu Items")
        worst = p.nlargest(7, "food_cost_pct")[["name", "qty_sold", "revenue",
                                                "food_cost_pct"]]
        _margin_table(worst, good=False)

    # ------------------------------------------------ daily trend
    if not b.daily.empty:
        theme.section("Daily Sales vs Theoretical Food Cost",
                      "from transaction-level POS export")
        d = b.daily.sort_values("date")
        fig = go.Figure()
        fig.add_scatter(x=d["date"], y=d["revenue"], name="Sales",
                        fill="tozeroy", line=dict(color=theme.BLUE, width=2),
                        fillcolor="rgba(31,95,168,0.08)")
        fig.add_scatter(x=d["date"], y=d["theo_cost"], name="Theoretical food cost",
                        fill="tozeroy", line=dict(color=theme.ACCENT, width=2),
                        fillcolor="rgba(14,124,102,0.10)")
        fig.update_layout(height=300, yaxis_tickprefix="$",
                          yaxis_tickformat=",.0f")
        st.plotly_chart(fig, use_container_width=True)

    # ------------------------------------------------ biggest price moves
    if not b.price_changes.empty:
        theme.section("Biggest Vendor Price Increases", "period first vs last delivery")
        pc = b.price_changes.head(6)[["vendor", "description", "first_price",
                                      "last_price", "pct_change", "dollar_impact"]]
        pc = pc.rename(columns={
            "vendor": "Vendor", "description": "Item",
            "first_price": "First $", "last_price": "Last $",
            "pct_change": "Δ %", "dollar_impact": "$ Impact"})
        st.dataframe(
            pc.style.format({"First $": "${:,.2f}", "Last $": "${:,.2f}",
                             "Δ %": "{:+,.1f}%", "$ Impact": "${:,.0f}"})
            .background_gradient(subset=["Δ %"], cmap="Reds"),
            use_container_width=True, hide_index=True)


def _margin_table(df: pd.DataFrame, good: bool) -> None:
    df = df.rename(columns={"name": "Item", "qty_sold": "Sold",
                            "revenue": "Revenue", "food_cost_pct": "Food Cost %"})
    cmap = "Greens_r" if good else "Reds"
    st.dataframe(
        df.style.format({"Sold": "{:,.0f}", "Revenue": "${:,.0f}",
                         "Food Cost %": "{:,.1f}%"})
        .background_gradient(subset=["Food Cost %"], cmap=cmap),
        use_container_width=True, hide_index=True, height=290)


@st.cache_data(show_spinner=False)
def _insights_key(n_rows: int, spend: float) -> None:
    return None


def _cached_insights(b):
    if "insights" not in st.session_state:
        st.session_state["insights"] = generate_insights(
            b.profit, b.variance, b.price_changes, b.purchases, b.exploded)
    return st.session_state["insights"]
